"""Use of the Transformation output by LLM2: prompt guidance + deterministic cross-check.

The refined transcript stays the SOURCE OF TRUTH. Guidance is model-generated and may be wrong.
"""
from __future__ import annotations

GUIDANCE_ADDENDUM = """

STRUCTURED GUIDANCE (model-generated by an earlier stage; NOT authoritative)
After the transcript you may receive a structured representation: topics, decision candidates and action candidates, each with segment indices and a status. It is a hint for organizing the documentation. The transcript is the only source of truth and the guidance may be wrong.
- Verify EVERY candidate against the transcript segments it cites (and neighbouring segments) before using it. Include it in decisions or action_items only if the transcript itself supports it. If you cannot verify it, omit it.
- Candidate statuses "proposed", "tentative" and "unresolved" are not decisions; a "confirmed" status is a claim you must check, not a fact. Re-judge from the transcript.
- Never copy an owner or deadline from the guidance unless the transcript explicitly states it. A candidate's owner/deadline being null means none was found.
- Keep conditions: a "conditional" action stays conditional in its task wording; do not present it as an unconditional commitment or hard deadline.
- You may use the guidance topics to organize the minutes, but still follow all MINUTES RULES (concise, no recap topics) and cite the real supporting segment indices. You may cite segments the guidance did not list, and ignore ones it did.
- Decision candidates may also carry a "consensus" (classification high/medium/low, an internal heuristic score, and the segment ids that caused it: decision statement, supporting, explicit agreement, opposition, unresolved), a "reconstructed" self-contained wording and the "context" segment ids it was built from. These are HINTS about where to look, not proof. Re-read those segments yourself: a decision belongs in "decisions" only if the transcript shows the meeting actually agreed/finalised it. If the guidance says confirmed/high but the segments contain unresolved, pending, opposed or merely proposed language, do NOT copy it: leave it out of "decisions" and state it as proposed/open in the minutes. Opposition or "not approved" language outweighs a high score. Never treat missing objection as agreement.
- A reconstructed wording may help you phrase a decision standalone, but write only what the transcript supports: keep negation, numbers, names, identifiers and uncertainty exactly, and add no fact the transcript lacks. If it differs from the transcript, trust the transcript.
- Do not mention the guidance, candidates or any earlier stage in the output. All ABSOLUTE RULES above still apply."""


def _decision_detail(x: dict) -> list[str]:
    """Extra, optional lines for a decision candidate (absent in older transformation outputs)."""
    out: list[str] = []
    c = x.get("consensus")
    if isinstance(c, dict):
        ev = c.get("evidence") or {}
        parts = [f"{k}={ev.get(k)}" for k in ("decision_statement", "supporting_statements", "explicit_agreement",
                                               "explicit_finalization", "opposition", "unresolved") if ev.get(k)]
        out.append(f"    consensus: {c.get('classification')} / {str(c.get('level')).upper()} "
                   f"(internal heuristic score {c.get('score')}, not a probability); evidence: "
                   + ("; ".join(parts) if parts else "none"))
    if x.get("reconstructed_text"):
        out.append(f"    reconstructed ({x.get('reconstruction_source')}): \"{x['reconstructed_text']}\"")
    if x.get("context_segments"):
        out.append(f"    context segments {x['context_segments']} (trigger {x.get('trigger_segment')}: "
                   f"\"{x.get('original_text')}\")")
    return out


def render_guidance(t: dict) -> str:
    """Compact text rendering of transformation_output.json for the LLM2 user prompt."""
    L = ["", "STRUCTURED GUIDANCE (not authoritative; verify against the transcript above)", "Topics:"]
    for x in t.get("topics", []):
        L.append(f"- {x['topic_id']}: {x['title']} (segments {x['segment_ids']})")
    L.append("Decision candidates:")
    for x in t.get("decision_candidates", []) or []:
        L.append(f"- {x['decision_id']} [{x['status']}] \"{x['text']}\" (segments {x['segment_ids']})")
        L += _decision_detail(x)
    if not t.get("decision_candidates"):
        L.append("- (none)")
    L.append("Action candidates:")
    for x in t.get("action_candidates", []) or []:
        L.append(f"- {x['action_id']} [{x['status']}] \"{x['description']}\" owner={x.get('owner')} "
                 f"deadline={x.get('deadline')} condition={x.get('condition')} (segments {x['segment_ids']})")
    if not t.get("action_candidates"):
        L.append("- (none)")
    rel = t.get("relations") or []
    if rel:
        L.append("Relations:")
        L += [f"- {r['from_segment']} {r['type']} {r['to_segment']}" for r in rel]
    return "\n".join(L)


def cross_check(parsed: dict, t: dict) -> list[str]:
    """Warnings (never edits) where LLM2's output disagrees with the guidance. Deterministic, id-overlap based."""
    w: list[str] = []
    cands = t.get("decision_candidates", []) or []
    acts = t.get("action_candidates", []) or []
    for k, d in enumerate(parsed["decisions"]):
        ov = [c for c in cands if set(c["segment_ids"]) & set(d.segment_ids)]
        if ov and not any(c["status"] == "confirmed" for c in ov):
            st = ",".join(sorted({c["status"] for c in ov}))
            w.append(f"decisions[{k}]: guidance rated the overlapping candidate(s) {st}, not confirmed; verify it was agreed")
    for k, a in enumerate(parsed["action_items"]):
        ov = [c for c in acts if set(c["segment_ids"]) & set(a.segment_ids)]
        if not ov:
            continue
        if a.owner and not any(c.get("owner") for c in ov):
            w.append(f"action_items[{k}]: owner '{a.owner}' not present in guidance; verify it is explicit in the transcript")
        if a.deadline and not any(c.get("deadline") for c in ov):
            w.append(f"action_items[{k}]: deadline '{a.deadline}' not present in guidance; verify it is explicit and committed")
        if any(c["status"] == "conditional" for c in ov) and not any(c["status"] != "conditional" for c in ov):
            w.append(f"action_items[{k}]: guidance marked this action conditional"
                     f" ({'; '.join(str(c.get('condition')) for c in ov if c.get('condition'))}); verify the wording keeps the condition")
    for k, d in enumerate(parsed["decisions"]):
        for c in [c for c in cands if set(c["segment_ids"]) & set(d.segment_ids)]:
            cons = c.get("consensus")
            if not isinstance(cons, dict):
                continue
            ev = cons.get("evidence") or {}
            if cons.get("classification") in ("unresolved", "contested", "proposed") or ev.get("opposition") or ev.get("unresolved"):
                w.append(f"decisions[{k}]: guidance consensus for {c['decision_id']} is "
                         f"{cons.get('classification')}/{cons.get('level')}"
                         f" (opposition={ev.get('opposition') or []}, unresolved={ev.get('unresolved') or []}); "
                         "verify the meeting actually agreed it")
                break
    covered = {i for d in parsed["decisions"] for i in d.segment_ids}
    for c in cands:
        if c["status"] == "confirmed" and not (set(c["segment_ids"]) & covered):
            w.append(f"guidance {c['decision_id']} (confirmed) is not in the final decisions (not verified against the transcript)")
    return w
